# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'PublisherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'OpenWrapSDK','1.6.2'
  # Pods for PublisherApp

end
